### ISSUE TITLE
Internalizar QRCoder

### ISSUE THREAD

**Issue by felipeleusin** [nfcerta/NFCerta.NFe#2]
Porque ter isso gerando uma DLL diferente somente para 1 arquivo .cs?

Qual a licença dele? Não dá para incluir somente o arquivo direto no NFe?

**Comment by vicentedealencar** [comment]
Inclui o projeto do jeito que estava, nem percebi que era apenas 1 .cs. 
O ideal seria referenciar eles via nuget, mas eles nao tem.

A licença é muito permisiva, boa.
